- README.md
Solution: Use a simple make command because there is no "check" compilation target for zmq projects
This PR also replaces some tabs with 4 spaces in the README
> Problem: compilation script from README fails on "make check" steps

- api/igsagent.api
- include/igsagent.h
- A parameter cannot be an `IGS_IMPULSION_T`
- The method has no definition
Solution: Remove the declaration from `igsagent.h` and `igsagent.api`
> Problem: igsagent.h defined igs_parameter_set_impulsion

- .gitmodules
Problem: on certain systems, sodium submodule does not follow the right branch.
Solution: Force submodule to follow the right branches.
> Make submodule follow specific branches

- src/igs_split.c
Problem : Impossible to re-create a splitter on an output when all workers have left the splitter.
Solution : Remove useless test + destroy splitter when all of its workers have left as incoming workers shall not receive data emitted when they where no workers
> Problem : Impossible to re-create a splitter on an output when all workers have left the splitter

- src/igs_parser.c
Compilation under Linux with GCC raises warnings in `igs_parser.c`. The warnings should be fixed.
Solution: Use boolean operator `&&` instead of binary operator `&` to compare boolean values.  
_I also realigned some multi-line statements I came across, without being exhaustive._
> Problem: GCC raises warnings about binary operator used to compare boolean values

- src/igs_network.c
Solution: Plug that leak.
We append strings to two zlist using `strdup` but both zlists are `autofree`.  
`autofree` means that the appended values will be copied automatically, therefore there is no need for `strdup`.
> Problem: There is a memory leak when participating in elections

- CMakeLists.txt
- builds/cmake/Packing-debian.cmake
**The package is not ready to be posted on Debian repository**  
It still has lintian errors and may not be validated by the Debian folks.  
Nonetheless, the package installs a complete version of the ingescape library and its dependencies.  
It can be put on a "private" repository and delivered through APT.
The package name is `ingescape-dev` so the APT command line to install the package would be `apt-get install ingescape-dev`
> Make a CPack target to build a .deb package on Debian

- .gitlab-ci.yml
- CMakeLists.txt
Solution: Do not pack previous debian builds as .deb packages.
Add a publish job to send .deb package to our own APT repository
> Problem: CMake update for Debian packaging broke previous debian jobs

- .gitlab-ci.yml
Solution: Build .deb packages on Debian old stable (currently Debian 10 buster)
> Problem: .deb packages built on Debian 11 have compatibility issues with older Debian

- CMakeLists.txt
Solution: Make static library build with position independent code using the -fPIC flag.
CMake provides an easy way to do this with `set(CMAKE_POSITION_INDEPENDENT_CODE ON)`
> Problem: Bindings cannot link against static version of the library because of position dependent code

- CMakeLists.txt
This means that there is no solution to have a fully statically linked stack.
Solution: Update the CMake chain so static libraries can be linked against static dependencies, providing a fully statically linked stack.  
This is handled by a CMake variable called `STATIC_ZMQ_LINK` introduced for this purpose.  
`STATIC_ZMQ_LINK` is ON by default by can be deactivated if needed.
Note: Changes had to be made in the submodules to read the `STATIC_ZMQ_LINK` variable.
> Problem: Static libraries built by our pipelines are linked against dynamic libraries

- CMakeLists.txt
- builds/qt/ingescape.pro
- include/igsagent.h
- include/ingescape.h
- include/ingescape_private.h
Both these macros help with `__declspec` declaration for API exports in Windows DLLs.
Previous `PUBLIC` macro was used in the code and never retired when fitting the project for ZeroMQ.
Then we had both `PUBLIC` and `INGESCAPE_EXPORT` macros for similar behaviors. Both used in the code.  
This PR retires the `PUBLIC` macro and replaces its previous uses with the `INGESCAPE_EXPORT` macro.
> Merge PUBLIC and INGESCAPE_EXPORT macros to have a single DLL export macro 

- include/ingescape.h
Update czmq because new fixes have been published. 
Patch version incremented to follow changes.
> Update czmq dependency

- .gitlab-ci.yml
Add missing dependency in "publish-python-package" job to gather libs for linux.
> Problem in "publish-python-package" job, linux libs cannot be found.

- CMakeLists.txt
There are issues when using a verison of ingescape library that was not built on a macOS version not using the same SDK as ours. CMake seems to link explicitly against a given version of macOS SDK.
Solution: Force `--sysroot` compilation parameter on macOS to the non-versioned SDK instead of the versioned one to be compatible with other versions.
> Problem: ingescape library compiled on a different version of macOS fails to link

- .gitlab-ci.yml
- bindings/python/.gitignore
- bindings/python/README.md
- bindings/python/includes/compat.h
- bindings/python/includes/ingescape_agent_python.h
- bindings/python/includes/ingescape_python.h
- bindings/python/includes/util.h
- bindings/python/prepare_setup.ps1
- bindings/python/prepare_setup.sh
- bindings/python/setup.py.in
- bindings/python/src/admin.c
- bindings/python/src/agent.c
- bindings/python/src/compat.c
- bindings/python/src/core.c
- bindings/python/src/ingescape_python.c
- bindings/python/src/monitor.c
- bindings/python/src/network.c
- bindings/python/src/util.c
Several fixes and improvements :  
- Compatibility with python 3.11
- Exception handling in the callbacks (prints out the exception then releases the interpreter lock)
- Fix agent events callback (context data weren't passed to the callbacks properly)
- Minor renaming to match the ingescape API
- Some fixes in reference counts (C side)
- CI pipelines updated to build more pre-built packages
> Update python binding

- bindings/javascript-node/package.json
- bindings/javascript-node/src/agent.c
- bindings/javascript-node/src/mapping.c
- bindings/javascript-node/tests/test.js
- bindings/javascript-node/types/index.d.ts
Add **clearMappingsForInput** method in Node JS binding, upgrade version to 3.4.0.
> Node JS binding update

- src/igsagent.c
Solution : remove notification of IGS_AGENT_KNOWS_US from remote agent in igsagent_activate method because remote agent doesn't know the igsagent at this point. This event will be notified when remote agent has acknowledged the newly activated igsagent.
> Problem : two "IGS_AGENT_KNOWS_US" received when an igsagent is activated after its creation

- src/igs_network.c
I had a BAD_ACCESS on a remote agent when igsagent_service_call method iterates over all remote agents and a remote agent leaves the network. igsagent_service_call is protected by the model_read_write_lock mutex at the start of the method BUT removing a remote agent in context loop is not protected (event "EXIT" and "REMOTE_AGENT_EXIT").
Solution : lock/unlock removing a remote agent in context loop.
> Problem: BAD_ACCESS in igsagent_service_call method

- src/igs_json_node.c
- src/yajl_tree.c
- src/yajl_tree.h
`igsyajl_tree_parse` uses `strlen` to get the size of the content to parse.   
While parsing a file, we give it a `zchunk` which is not null-terminated.
Solution: Do not use `strlen` to get the size of the input to parse and give the size directly as a parameter to `igsyajl_tree_parse`.
> Problem: internal JSON parsing method igsyajl_tree_parse causes a head-buffer-overflow error

- bindings/python/src/network.c
- bindings/python/tests/global_api.py
Because we "encode" the string from the lib instead of "decoding" it into a PyObject.
Solution: Make a proper PyObject from the devices names and let the python interpreter handles their refcount and life cycle.
> Problem: net_devices_list() API in python make agents crash

- bindings/python/src/agent.c
- bindings/python/src/core.c
Passing `bytes` to a service DATA arg seems to send garbage, at least in front of the real DATA.
Passing `bytearray` straight throws an OOM error, event when passing just a few bytes.
It appears that the python wrapper uses the wrong python C-API to pass DATA to `igs_service_args_add_data` resulting in conversion error or wrong memory block passed to ingescape.
Solution: Check if passed python object is of types `bytes` or `bytearray` and use the proper APIs to convert python data object to C `char*`
NOTE: There is still problems with sending DATA as output.
An other PR should follow with corrections about that (related issue #67).
> DATA handling in service args

- bindings/python/src/network.c
A typo in the parsing format string causes crashes.
Solution: Fix that typo
> Problem: [python binding] using timers causes segfault

- include/ingescape.h
- src/igs_service.c
Solution: Always free the args list when using igsagent_service_call, as stated in the documentation.
I also incremented the PATCH version number to publish this new version, including previous PR that were still on the previous version (mostly python bindings fixes)
> Problem: The arguments list passed to igsagent_service_call may be leaked in a specific error case

- src/igs_network.c
A variable used in a loop is freed but not set to NULL. The next loop iteration may cause a double-free if the variable is not reallocated.
Solution: Use `freen` macro from czmq to ensure that freed variables are also set to NULL.
ASAN report of the double-free error
```
=================================================================
==34283==ERROR: AddressSanitizer: attempting double-free on 0x602000021fb0 in thread T5:
#0 0x7ffff6f026b8 in __interceptor_free ../../.././libsanitizer/asan/asan_malloc_linux.cc:45
#1 0x7ffff6bbb4ee in s_handle_publication /appli/ckr/comp/src/ingescape/src/igs_network.c:311
#2 0x7ffff6bc7223 in s_manage_zyre_incoming /appli/ckr/comp/src/ingescape/src/igs_network.c:1534
#3 0x7ffff691f871 in zloop_start …
```
> Problem: Crashes due to a double-free encountered when receiving a publication from other agents

- include/ingescape_private.h
They are already accessible on the other platforms.
Solution: Make those mapping/split methods 'exported' with using the private API on Windows
> Problem: Some parts of the private API (that do not alter the model) are not 'exported' to be accessible on Windows

- bindings/python/src/network.c
- bindings/python/tests/global_api.py
- bindings/python/tests/run_tests.sh
- bindings/python/tests/security/private.cert_secret
- bindings/python/tests/security/public.cert
The wrapper code declares that it needs 2 parameters but then only accepts one in its code.
Solution: Both parameters must be taken into account and passed to the C API.  
I also added test code corresponding to enable_security to catch future problems.
> Problem: enable_security API throws an exception upon use

- include/ingescape.h
- src/igs_network.c
Timer callback can be executed at the same time as another thread calls the igs_timer_stop method and thus access a freed pointer of an igs_timer_t.
Solution: Add same mutex as in creation/deletion in the timeout callback to access the igs_timer_t
> Problem: igs timer callback is not thread safe 

- include/ingescape.h
- src/igs_network.c
Introduced in the previous PR 
Solution: unlock the mutex before the call of the user igs timer callback
> Problem : deadlock in igs methods used in igs timer callback

- .gitlab-ci.yml
- bindings/javascript-node/.npmignore
The fix only consists of removing some files from the `.npmignore` file.  
This PR also includes changes to the pipeline to build the nodejs binding for both darwin-x64 and darwin-arm64.
> Include prebuilds into NPM package

- .gitlab-ci.yml
Since the old runner tag has been changed, .gitlab-ci.yml must be updated accordingly.
> Change old OSX runner job tag

- CMakeLists.txt
The "major" shared file name is `libingescape.3.0.0.dylib` instead of `libingescape.3.dylib`. The same thing happens on linux.
Solution: Change the CMakeLists.txt so the major lib (called `SOVERSION`) version has the correct name.
> Problem: The "major" shared library file on Unix system has the wrong name

- src/igs_network.c
Hi,
This PR is fixing when build in release :
```
igsPartner --device eth0
*** buffer overflow detected ***: terminated
Aborted (core dumped)
```
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f15b9ba826e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f15b9b8b8ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007f15b9b8c7b6 in __libc_message_impl (fmt=fmt@entry=0x7f15b9d31765 "*** %s ***: terminated\n") at ../sysdeps/posix/libc_fatal.c:132
#6  0x00007f15b9c99c19 in __GI___fortify_fail …
```
> fix buffer overflow detected

- src/igs_model.c
- src/igs_parser.c
- src/igs_split.c
- test/src/tester.c
Helped catch a possible issue in igs_split.c where we used the global core_context instead of the one given in parameter.  
[Link in the diff](https://github.com/zeromq/ingescape/compare/main...Mathsoum:ingescape:compilation_warnings?expand=1#diff-e6e2405d5c57e8b6a31d83877f718645dd668e223a1bb8a590e2bc75be6c4d39R497)
> Fix a bunch of compilation warnings
